### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by abhinavm24** [renzhengyu/duolingo-bot#6]
I have no idea how to use this project. If you can list out the steps. I'm more than happy to update the readme with more details

**Comment by zacharyqueralt** [comment]
I agree, it seems like a great piece of software. I'm in the process of figuring it out and ill let u know if I do. I'm happy to make a guide on my website or the wiki and also a GUI in VS for it if the creators want.

**Comment by rcheating** [comment]
Please do let me know. A GUI would be interesting as well. And a guide
would be invaluable

**Comment by slf188** [comment]
I'm also interested in learning how this piece of software works...
